name=Fast PWM Pin
version=0.3.2504
author=Maxint
maintainer=Maxint R&D <mm_rd@maxint.nl>
sentence=Enable fast PWM on a specific output pin.
paragraph=Generate a very fast (or very slow) PWM signal on a specific output pin at a specified frequency. Examples included.
category=Signal Input/Output
url=https://github.com/maxint-rd/FastPwmPin
architectures=*